Name-AMRIT DUBEY , Reg No-24-27-09 , Programme-MTECH DATA SCIENCE, Assignment Number-02

In [2]:
#Q1)a)Create a variable named var1 that stores an array of numbers from 0 to 30,inclusive. Print var1 and its shape. Hint : arange
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Print the array and its shape
print("Array:", var1)
print("Shape:", var1.shape)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape: (31,)


In [3]:
#Q1)b)Change var2 to a validly-shaped two-dimensional matrix and store it in a
#new variable called var2. Print var2 and its shape. Hint: Use the reshape function
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Reshape var1 into a 2D matrix with valid dimensions (e.g., 5 rows and 6 columns)
# Note: The total number of elements (31) must match the product of the dimensions
# Since 31 cannot be reshaped exactly into equal dimensions, we'll reshape into (31, 1)
var2 = var1.reshape(31, 1)

# Print the reshaped matrix and its shape
print("Reshaped Array (var2):")
print(var2)
print("Shape of var2:", var2.shape)


Reshaped Array (var2):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Shape of var2: (31, 1)


In [4]:
#Q1)c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
#Print var3 and its shape.
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Reshape var1 into a valid three-dimensional matrix
var3 = var1.reshape(31, 1, 1)

# Print the reshaped 3D matrix and its shape
print("Reshaped Array (var3):")
print(var3)
print("Shape of var3:", var3.shape)


Reshaped Array (var3):
[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]
Shape of var3: (31, 1, 1)


In [5]:
#Q1)d) Use two-dimensional array indexing to set the first value in the second row of var2
#to -1. Now look at var1 and var3. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Reshape var1 into a 2D matrix with shape (31, 1)
var2 = var1.reshape(31, 1)

# Modify the first value in the second row of var2
var2[1, 0] = -1

# Print var1, var2, and var3 to see if they are affected
var3 = var1.reshape(31, 1, 1)

print("Modified var2:")
print(var2)

print("\nvar1 after modifying var2:")
print(var1)

print("\nvar3 after modifying var2:")
print(var3)


Modified var2:
[[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]

var1 after modifying var2:
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

var3 after modifying var2:
[[[ 0]]

 [[-1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


In [6]:
#Q1)e) Another thing that comes up a lot with array shapes is thinking about how to
#aggregate over specific dimensions. Figure out how the NumPy sum function
#works (and the axis argument in particular) and do the following:
#(i) Sum var3 over its second dimension and print the result.
#(ii) Sum var3 over its third dimension and print the result.
#(iii) Sum var3 over both its first and third dimensions and print the result.
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Reshape var1 into a 3D matrix with shape (31, 1, 1)
var3 = var1.reshape(31, 1, 1)

# (i) Sum var3 over its second dimension (axis=1)
sum_axis_2 = np.sum(var3, axis=1)
print("Sum over the second dimension (axis=1):")
print(sum_axis_2)

# (ii) Sum var3 over its third dimension (axis=2)
sum_axis_3 = np.sum(var3, axis=2)
print("\nSum over the third dimension (axis=2):")
print(sum_axis_3)

# (iii) Sum var3 over both its first and third dimensions (axis=(0, 2))
sum_axis_1_3 = np.sum(var3, axis=(0, 2))
print("\nSum over both the first and third dimensions (axis=(0, 2)):")
print(sum_axis_1_3)


Sum over the second dimension (axis=1):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]

Sum over the third dimension (axis=2):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]

Sum over both the first and third dimensions (axis=(0, 2)):
[465]


In [7]:
#Q1)f) Write code to do the following:
#(i) Slice out the second row of var2 and print it.
#(ii) Slice out the last column of var2 using the -1 notation and print it.
#(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
import numpy as np

# Create an array of numbers from 0 to 30 inclusive
var1 = np.arange(0, 31)

# Reshape var1 into a 2D matrix (for example, 6 rows and 5 columns)
# Since var1 has 31 elements, let's reshape it into 6 rows and 5 columns
# (we'll manually trim it to make it a 6x5 matrix)
var1 = var1[:30]  # Trim the array to 30 elements
var2 = var1.reshape(6, 5)

# (i) Slice out the second row of var2 and print it
second_row = var2[1, :]
print("Second row of var2:")
print(second_row)

# (ii) Slice out the last column of var2 using the -1 notation and print it
last_column = var2[:, -1]
print("\nLast column of var2:")
print(last_column)

# (iii) Slice out the top-right 2 × 2 submatrix of var2 and print it
top_right_2x2_submatrix = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:")
print(top_right_2x2_submatrix)


Second row of var2:
[5 6 7 8 9]

Last column of var2:
[ 4  9 14 19 24 29]

Top-right 2x2 submatrix of var2:
[[3 4]
 [8 9]]


In [8]:
#Q2a) The most basic kind of broadcast is with a scalar, in which you can perform a
#binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
#perform that operation with the scalar for every element of the array. To try this
#out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
import numpy as np

# Create an array with values from 0 to 9 using arange
vector = np.arange(10)

# Add 1 to each element of the array (broadcasting)
vector = vector + 1

# Print the result
print("Vector from 1 to 10:")
print(vector)


Vector from 1 to 10:
[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Q2(b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
#using the vector you just created, and adding it to a reshaped version of itself.
import numpy as np

# Create a vector with values from 1 to 10
vector = np.arange(1, 11)

# Reshape the vector to be a column vector (10x1) for row indices (i)
row_vector = vector.reshape(10, 1)

# Create the matrix A using broadcasting by adding the row_vector to the vector
A = row_vector + vector

# Print the resulting matrix A
print("Matrix A (10x10) where A[i, j] = i + j:")
print(A)


Matrix A (10x10) where A[i, j] = i + j:
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [10]:
#Q2)c) A very common use of broadcasting is to standardize data, i.e., to make it have
#zero mean and unit variance. First, create a fake “data set” with 50 examples,
#each with five dimensions.
#import numpy.random as npr
#data = np.exp(npr.randn ( 50 , 5 ) )
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the generated dataset
print("Fake dataset (50 examples, 5 dimensions):")
print(data)


Fake dataset (50 examples, 5 dimensions):
[[ 0.71521909  0.73621951  1.86602102  0.29541012  1.04049409]
 [ 1.67936141  0.36953901  0.75979869  2.1547379   0.8116442 ]
 [ 0.56989138  1.98756482  0.53010802  0.47615648  0.37656725]
 [ 0.29749536  1.35928597  2.04922739  2.75444182  0.20293478]
 [ 0.41388884  1.03303532  0.33372439  7.2429837   0.95593827]
 [ 0.39432497  1.61111176  0.57935725  0.99650493  1.07471056]
 [ 0.23485761  0.14998533  1.15027381  1.72688601  8.3663404 ]
 [ 0.26747773  3.71615168  0.45552664  0.46193516  3.67371046]
 [ 6.33519362  0.22421763  1.76539993  0.60166648  3.14958224]
 [ 1.41659352  0.26044346  0.10042283  1.12416155  0.97037118]
 [ 0.209365    1.84536737  3.52102973  0.71512422  1.06976507]
 [ 3.91829484  0.61451816  0.12123926  3.69667047  0.41359823]
 [ 0.48135632  0.34498742  4.00218435  6.32760103  1.21837911]
 [ 3.46982565  0.90775636  1.33389702  0.71767863  2.38552164]
 [ 2.55306551  2.29985996  2.34902005  0.10576246  1.0499357 ]
 [ 0.61756312

#Q2)You don’t worry too much about what this code is doing at this stage of the
#course, but for completeness: it imports the NumPy random number generation
#library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend
#data set of 50 independent and identically-distributed vectors from a log-normal distribution.

#Importing NumPy's random number generation library: The code uses NumPy, specifically the module for generating random numbers. 
#This module is often used in simulations or when working with random data.

#Generating a 50 × 5 matrix of standard normal random variates: The code creates a matrix of shape 50 rows and 5 columns.
#The values in this matrix are drawn from a standard normal distribution, meaning they have a mean of 0 and a standard deviation of 1.

#Exponentiating the generated values: Once the matrix is generated, the code exponentiates the values. 
#This means each element in the matrix is transformed by applying the exponential function (i.e., e^x). This changes the distribution of the data from normal to log-normal.

#Effect: The final result is a data set that consists of 50 vectors, each of length 5, where the elements of the vectors are from a log-normal distribution. 
#This kind of transformation is often used to model data where values are skewed and cannot be negative, which is common in financial and biological contexts.


In [12]:
#Q2)e) Now, compute the mean and standard deviation of each column. This should
#result in two vectors of length 5. You’ll need to think a little bit about how to use
#the axis argument to mean and std. Store these vectors into variables and print both of them.
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean of each column
mean_vector = np.mean(data, axis=0)

# Compute the standard deviation of each column
std_vector = np.std(data, axis=0)

# Print the results
print("Mean of each column:")
print(mean_vector)

print("\nStandard deviation of each column:")
print(std_vector)


Mean of each column:
[2.04593116 1.89271734 1.49838427 1.82208732 1.91299886]

Standard deviation of each column:
[3.47604642 1.91866001 1.45995066 1.98766685 2.64063026]


In [13]:
#Q2)f) Now standardize the data matrix by 1) subtracting the mean off of each column,
#and 2) dividing each column by its standard deviation. Do this via broadcasting,
#and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of
#the columns of normalized and print them out.
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation of each column
mean_vector = np.mean(data, axis=0)
std_vector = np.std(data, axis=0)

# Standardize the data using broadcasting
normalized = (data - mean_vector) / std_vector

# Print the normalized data
print("Normalized data matrix:")
print(normalized)

# Verify by computing the mean and standard deviation of the columns of normalized
mean_normalized = np.mean(normalized, axis=0)
std_normalized = np.std(normalized, axis=0)

# Print the mean and standard deviation of the normalized data
print("\nMean of each column in normalized data:")
print(mean_normalized)

print("\nStandard deviation of each column in normalized data:")
print(std_normalized)


Normalized data matrix:
[[ 3.77246970e-01 -1.27526455e-01 -2.71681024e-01  3.75436999e-01
  -4.08981038e-01]
 [ 1.50409138e+00 -7.14399388e-01  5.75955149e+00 -4.86245244e-01
  -2.63257128e-01]
 [-1.00895809e+00  1.03669448e+00 -8.07034040e-02  2.93593118e-01
  -3.27615212e-01]
 [ 9.46417218e-01 -7.17074905e-01 -1.25487879e-01 -3.71749416e-01
  -5.28615162e-01]
 [-4.08945528e-01  1.90295667e-01 -2.45935474e-01  1.10739348e+00
  -5.95795049e-01]
 [-7.42026221e-01 -5.09920566e-01 -2.57944553e-01 -5.00737382e-01
  -6.10500901e-01]
 [-8.72728179e-01 -5.55511916e-01 -3.84106932e-01 -4.40137952e-01
  -6.88054879e-01]
 [-5.64487373e-01  1.81669453e-01 -3.64212133e-01  1.03954896e+00
  -3.50994901e-01]
 [ 7.81891765e-01  4.78584852e-02 -1.07269106e-01  2.14843395e-01
  -4.75806130e-01]
 [-4.63359716e-01 -8.80436194e-01 -4.09096964e-01 -6.68650727e-01
   1.73602133e-01]
 [-9.14308579e-01  1.36103823e+00 -3.66210859e-01  1.21407813e+00
  -2.97237382e-01]
 [-7.96545996e-01 -5.76846175e-01 -1.8385

In [14]:
#Q3)a) A Vandermonde matrix is a matrix generated from a vector in which each column
#of the matrix is an integer power starting from zero. So, if I have a column vector [x1, x2, . . . , xN] T,
#then the associated (square) Vandermonde matrix would be 
#Use what you learned about broadcasting in the previous problem to write a
#function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
#for any N. Do it without using a loop. Here’s a stub to get you started:
#Use your function for N = 12, store it in variable named vander, and print the result.

import numpy as np

def vandermonde(N):
    # Create the vector [1, 2, ..., N]
    vec = np.arange(N) + 1
    
    # Generate the Vandermonde matrix using broadcasting
    vander = vec ** np.arange(N).reshape(-1, 1)
    
    return vander

# Use the function for N = 12
vander = vandermonde(12)

# Print the resulting Vandermonde matrix
print("Vandermonde matrix for N=12:")
print(vander)


Vandermonde matrix for N=12:
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           3           4           5           6
            7           8           9          10          11          12]
 [          1           4           9          16          25          36
           49          64          81         100         121         144]
 [          1           8          27          64         125         216
          343         512         729        1000        1331        1728]
 [          1          16          81         256         625        1296
         2401        4096        6561       10000       14641       20736]
 [          1          32         243        1024        3125        7776
        16807       32768       59049      100000      161051      248832]
 [          1          64         729        4096       15625       46656
   

In [15]:
#Q3)b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
#of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
#vander with the vector you just created and store that in a new vector and call it b. Print the vector b.

import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = vec ** np.arange(N).reshape(-1, 1)
    return vander

# Create the Vandermonde matrix for N = 12
vander = vandermonde(12)

# Create a vector of all ones of length 12
x = np.ones(12)

# Perform matrix-vector multiplication
b = vander @ x  # or you can use np.dot(vander, x)

# Print the resulting vector b
print("Vector b (result of matrix-vector multiplication):")
print(b)


Vector b (result of matrix-vector multiplication):
[1.20000000e+01 7.80000000e+01 6.50000000e+02 6.08400000e+03
 6.07100000e+04 6.30708000e+05 6.73595000e+06 7.33994040e+07
 8.12071910e+08 5.02098436e+08 3.98488294e+09 6.74822371e+09]


In [16]:
#Q3)c) First, solve the linear system the naïve way, pretending like you don’t know x.
#Import numpy.linalg, invert V and multiply it by b. Print out your result. What
#should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.

import numpy as np
import numpy.linalg as la

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = vec ** np.arange(N).reshape(-1, 1)
    return vander

# Create the Vandermonde matrix for N = 12
vander = vandermonde(12)

# Create a vector of all ones of length 12
x = np.ones(12)

# Perform matrix-vector multiplication
b = vander @ x  # This is our result vector

# Solve the linear system by inverting the Vandermonde matrix
x_hat = la.inv(vander) @ b

# Print the resulting vector x_hat
print("Result of solving the linear system (x_hat):")
print(x_hat)


Result of solving the linear system (x_hat):
[0.99996236 1.00004554 0.99998787 1.00000833 0.99999357 1.00000279
 0.99999964 0.99999991 0.99999995 1.00000004 1.         1.        ]


In [17]:
#Q3)d) Now, solve the same linear system using solve. Print out the result. Does it seem
#more or less in line with what you’d expect?

import numpy as np
import numpy.linalg as la

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = vec ** np.arange(N).reshape(-1, 1)
    return vander

# Create the Vandermonde matrix for N = 12
vander = vandermonde(12)

# Create a vector of all ones of length 12
x = np.ones(12)

# Perform matrix-vector multiplication to create b
b = vander @ x  # This is our result vector

# Solve the linear system using np.linalg.solve
x_hat_solve = la.solve(vander, b)

# Print the resulting vector x_hat_solve
print("Result of solving the linear system using solve (x_hat_solve):")
print(x_hat_solve)


Result of solving the linear system using solve (x_hat_solve):
[0.99999981 1.00000104 0.99999744 1.00000355 0.99999713 1.00000123
 0.99999984 0.99999996 0.99999998 1.00000002 1.         1.        ]
